In [24]:
import numpy as np

np_array = np.array([1,2,3,4])
np_array
print(type(np_array))

print(np_array.dtype)

<class 'numpy.ndarray'>
int64


In [3]:
# list vs numpy array speed test

import time

size = 1000000

py_list = list(range(size))
start = time.time()
py_result = [x * 2 for x in py_list]
print("Python list time:", time.time() - start)

np_array = np.arange(size)
start = time.time()
np_result = np_array * 2
print("NumPy array time:", time.time() - start)

Python list time: 0.021726131439208984
NumPy array time: 0.0009701251983642578


In [4]:
try:
    print(py_list + 10)
except Exception as e:
    print("Error with list:", e)

print("NumPy array + 10:", np_array + 10)

Error with list: can only concatenate list (not "int") to list
NumPy array + 10: [     10      11      12 ... 1000007 1000008 1000009]


In [5]:
# numpy broadcasting
arr = np.array([1, 2, 3])
arr + 10

array([11, 12, 13])

In [25]:
a = np.arange(1, 10, 2)
print(a.dtype)


int64


In [11]:
np.linspace(10, 11)


array([10.        , 10.02040816, 10.04081633, 10.06122449, 10.08163265,
       10.10204082, 10.12244898, 10.14285714, 10.16326531, 10.18367347,
       10.20408163, 10.2244898 , 10.24489796, 10.26530612, 10.28571429,
       10.30612245, 10.32653061, 10.34693878, 10.36734694, 10.3877551 ,
       10.40816327, 10.42857143, 10.44897959, 10.46938776, 10.48979592,
       10.51020408, 10.53061224, 10.55102041, 10.57142857, 10.59183673,
       10.6122449 , 10.63265306, 10.65306122, 10.67346939, 10.69387755,
       10.71428571, 10.73469388, 10.75510204, 10.7755102 , 10.79591837,
       10.81632653, 10.83673469, 10.85714286, 10.87755102, 10.89795918,
       10.91836735, 10.93877551, 10.95918367, 10.97959184, 11.        ])

In [13]:
np.zeros(5)
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
# a = np.full(5,7)
b = np.full((1,2), -1)
b

array([[-1, -1]])

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])